# Generated by Django 3.2.5 on 2021-07-06 07:17
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=50)),
                ("org", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "date_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
