# Generated by Django 3.2.5 on 2021-07-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_domain_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='domain_name',
        ),
    ]
