# Generated by Django 3.2.5 on 2021-07-06 07:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_name_domain_domain_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="date_updated",
        ),
    ]
