# Generated by Django 3.2.5 on 2021-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_domain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.SmallIntegerField(),
        ),
    ]
