# Generated by Django 3.2.5 on 2021-07-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_status_domain_live'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='live',
            new_name='status',
        ),
    ]
