# Generated by Django 3.2.5 on 2021-07-06 07:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain",
            old_name="domain",
            new_name="name",
        ),
    ]
